apiVersion: v1
kind: Service
metadata:
  name: nest-app
  namespace: shopping-store
spec:
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  selector:
    app: nest-app
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nest-app
  namespace: shopping-store
spec:
  selector:
    matchLabels:
      app: nest-app
  replicas: 1
  template:
    metadata:
      labels:
        app: nest-app
    spec:
      containers:
      - name: nest-app
        image: shopping-store:latest # Replace with ECR URI
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secret
